# Generated by Django 4.0.4 on 2022-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0003_task_delete_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='value',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-Do', 'To-Do'), ('In progress', 'In progress'), ('Finished', 'Finished'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='To-Do', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
