# Generated by Django 4.0.4 on 2022-06-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carengine',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
