# Generated by Django 4.0.4 on 2022-06-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_care_ngine_carlisting_car_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='car_brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carBrend', to='cars.carbrend'),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='car_engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carEngine', to='cars.carengine'),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carModel', to='cars.carmodel'),
        ),
    ]
