# Generated by Django 4.0.4 on 2022-06-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carlisting_car_brend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
