version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  migration:
    build: .
    command: python manage.py migrate 
    volumes:
      - .:/code
    depends_on:
      - db 

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev  
    depends_on:
      - db
      - migration
  
  redis:
    image: 'redis:alpine'
    depends_on:
      - db

  celery_worker:
    build: ./
    entrypoint: celery
    command: -A news_agregator worker --loglevel=info
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    build: ./
    entrypoint: celery
    command: -A news_agregator beat
    depends_on:
      - db
      - redis
      - web
      - celery_worker   
