# Generated by Django 3.2.15 on 2022-10-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='comment',
            new_name='comment_like',
        ),
    ]
